Update to 64-bit Bluetooth stack from mido https://github.com/zeelog/android_device_xiaomi_mido/blob/lineage-22.1/proprietary-files.txt#L65 Also drop unnecessary android.hardware.bluetooth@1.0-service and 32-bit com.qualcomm.qti.ant@1.0-impl
error: vendor/samsung/gta2xlwifi/Android.bp:499:1: dependency "android.hardware.bluetooth@1.0-impl-qti" of "com.qualcomm.qti.ant@1.0-impl" missing variant:
  os:android,image:vendor,arch:arm_armv8-a_cortex-a53,link:shared
available variants:
  os:android,image:vendor,arch:arm64_armv8-a_cortex-a53,link:static
  os:android,image:vendor,arch:arm64_armv8-a_cortex-a53,link:shared